language: ruby
cache: bundler
sudo: false

before_install:
  - wget -O vault.zip -q https://releases.hashicorp.com/vault/0.6.0/vault_0.6.0_linux_amd64.zip
  - unzip vault.zip
  - mkdir ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"

branches:
  only:
    - master

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2

before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:schema:load
  - bundle exec rake app:db:test:prepare
