language: ruby
cache: bundler
sudo: false

env:
  - VAULT_VERSION=0.6.0
  - VAULT_VERSION=0.5.3
  - VAULT_VERSION=0.4.1
  - VAULT_VERSION=0.3.1

before_install:
  - wget -O vault.zip -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
  - unzip vault.zip
  - mkdir ~/bin
  - mv vault ~/bin
  - export PATH="~/bin:$PATH"

branches:
  only:
    - master

rvm:
  - 2.0
  - 2.1
  - 2.2

before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:schema:load
  - bundle exec rake app:db:test:prepare
